# ibmpcjr.toml
# Machine Configurations for the IBM PCJR

# MartyPC will search all *.toml files in 'machine' directories for machine
# configurations, so if you create a custom machine configuration, you can 
# put it in a separate file.
#
# ----------------------------------------------------------------------------
# Defining a Machine Configuration  
# Valid Machine types:
#  "Ibm5150v64K"
#  "Ibm5150v256K"
#  "Ibm5160"
#
# Valid Floppy Disk Controller types:
#  "IbmNec"
#
# Valid floppy Drive Types:
#  "360k"
#  "720k"
#  "1.2m"
#  "1.44m"

# Valid Hard Disk Controller Types:
#  "IbmXebec"
#
# Valid Serial Controller Types:
#  "IbmAsync"
#
# Conventional memory amount may be different from value specified due to MMIO
# optimizations. I recommend specifying a value in 0x10000 increments.
# ----------------------------------------------------------------------------

[[machine]]
name = "ibm_pcjr"
type = "IbmPCJr"
rom_set = "ibm_pcjr"
speaker = true
overlays = [
    "us_modelf_keyboard",
]

    [machine.memory]
    conventional.size = 0xA0000
    conventional.wait_states = 0

    # Video cards
    [[machine.video]]
    bus_type = "Onboard"
    type = "TGA"
    clock_mode = "Default"
