# machine_config_overlays.toml
# Main Machine Configuration Overlay file for MartyPC.

[[overlay]]
name = "xebec"
    # Hard disk controller
    [overlay.hdc]
    type = "IbmXebec"
        
[[overlay]]
name = "cga"
    # Video card
    [[overlay.video]]               
    type = "CGA"
    
    # Clocking mode for video card. Default values are:
    # Default   - Choose the best mode per card. (Recommended)
    # Dynamic   - Switch between supported clocking modes as required.
    # Cycle     - Clock by cycle. Accurate but slow. Only really useful for debugging.
    #             Only valid for CGA.
    # Character - Clock by character. Faster but may not be able to emulate certain effects.
    #             Valid for MDA, CGA and EGA.
    # Scanline  - Clock by scanline. Fastest but unable to emulate certain effects.
    #             (Unimplemented)
    clocking_mode = "Default"
    
    # Request line doubling for 15Khz (200 scanline) modes during rendering. 
    # Recommended.
    # This occurs before aspect correction, so reduces blur. Not applicable
    # to VGA as VGA double-scans such modes in hardware.
    line_double = true
    snow = false

[[overlay]]
name = "mda"
    # Video card
    [[overlay.video]]               
    type = "MDA"
    clock_mode = "Default"

[[overlay]]
name = "ega"
    # Video card
    [[overlay.video]]               
    type = "EGA"
    clock_mode = "Default"

[[overlay]]
name = "cga_and_mda"
    # Video card
    [[overlay.video]]               
    type = "CGA"
    clock_mode = "Default"
    # Video card
    [[overlay.video]]               
    type = "MDA"
    clock_mode = "Default"
    
#[[overlay]]
#name = "ram_expansion"
#    [[overlay.ram_expansion]]
#    type = "Conventional"
#    size = 0x60000  # 394K
#    speed_ns = 200
#    wait_states = 0
    
[[overlay]]
name = "four_floppies"
    # Floppy disk controller
    [overlay.fdc]
    type = "IbmNec"
        # Drives connected to controller. Maximum of 4.
        [[overlay.fdc.drive]]
        type  = "360k"
        [[overlay.fdc.drive]]
        type  = "360k"   
        [[overlay.fdc.drive]]
        type  = "360k"
        [[overlay.fdc.drive]]
        type  = "360k"       