[workspace]
members = [
    "core",
    "frontend_libs/render",
    "frontend_libs/pixels_stretch_renderer",
    "frontends/martypc_pixels_wasm32",
    "frontends/martypc_pixels_desktop"
]

[package]
name = "martypc"
version = "0.1.3"
edition = "2021"
license = "MIT"

[[bin]]
name = "martypc"
path = "frontends/martypc_pixels_desktop/src/main.rs"

[dependencies]
marty_core = { path = "core/"}
marty_render = { path = "frontend_libs/render"}
martypc_pixels_desktop = { path = "frontends/martypc_pixels_desktop"}

[profile.release]
#lto = true
#strip = true 

[features]
devtools = ["martypc_pixels_desktop/devtools"]
arduino_validator = ["marty_core/arduino_validator", "martypc_pixels_desktop/arduino_validator"]
cpu_validator = ["marty_core/cpu_validator", "martypc_pixels_desktop/cpu_validator"]
ega = ["marty_core/ega"]
vga = ["marty_core/vga"]


[build-dependencies]
winres = "0.1"

[[bench]]
name = "cga_bench"
harness = false

[[bench]]
name = "render_bench"
harness= false

[[bench]]
name = "cpu_bench"
harness = false