[workspace]
members = [
    "core",
    "frontend/render"
]

[package]
name = "martypc"
version = "0.1.2"
edition = "2021"

[[bin]]
name = "martypc"
path = "frontend/main.rs"

[dependencies]
marty_core = { path = "./core/"}
marty_render = { path = "./frontend/render"}
cpal = "0.13.5"
#egui = "0.20"
emath = "0.20"
#egui-wgpu = "0.21"
#egui-winit = { version = "0.20", default-features = false, features = ["links"] }
env_logger = "0.9"
image = { version = "0.24.2", default-features = false, features = ["png"] }
log = "0.4"
pixels = "0.12.1"
rand = "0.8.5"
regex = "1.5.5"
resize = "0.7.4"
rgb = "0.8.33"
serialport = "4.2.0"
winit = "0.27"
winit_input_helper = "0.13"

[dependencies.egui]
git = "https://github.com/emilk/egui.git"
rev = "f222ee044edf8beebfaf5dd7be15c9f318f20886"

[dependencies.egui-wgpu]
git = "https://github.com/emilk/egui.git"
rev = "f222ee044edf8beebfaf5dd7be15c9f318f20886"

[dependencies.egui-winit]
git = "https://github.com/emilk/egui.git"
rev = "f222ee044edf8beebfaf5dd7be15c9f318f20886"

[dev-dependencies]
criterion = "0.5.1"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
#lto = true
#strip = true 

[features]
arduino_validator = ["marty_core/arduino_validator"]
cpu_validator = ["marty_core/cpu_validator"]
ega = ["marty_core/ega"]
vga = ["marty_core/vga"]

[build-dependencies]
winres = "0.1"

[[bench]]
name = "cga_bench"
harness = false

[[bench]]
name = "render_bench"
harness= false

[[bench]]
name = "cpu_bench"
harness = false