# romdef_glabios.toml
# ROM definition file for MartyPC.

# ----------------------------------------------------------------------------
# ROM definitions for GLaBIOS
# ----------------------------------------------------------------------------
[[romset]]
alias = "glabios_pc"
priority = 0
provides = ["expansion", "ibm5150"]
desc = "GLaBIOS for IBM 5150 (MartyPC)"
rom = [
    { filename = "GLABIOS_0.2.5_8PC.ROM", addr = 0xFE000, size = 8192, chip = "glabios" }
]

[[romset]]
alias = "glabios_xt"
priority = 0
provides = ["expansion", "ibm5160"]
desc = "GLaBIOS for IBM 5160 (MartyPC)"
rom = [
    { filename = "GLABIOS_0.2.5_8XC.ROM", addr = 0xFE000, size = 8192, chip = "glabios" }
]

[[romset]]
alias = "glabios_xt_lp"
priority = 0
provides = ["expansion", "ibm5160"]
desc = "GLaBIOS for IBM 5160 (MartyPC + Lightpen)"
rom = [
    { filename = "GLABIOS_0.2.5_8TC_PEN.ROM", addr = 0xFE000, size = 8192, chip = "glabios" }
]

