[package]
name = "display_scaler"
version = "0.2.0"
edition = "2021"
license = "MIT"

[lib]
name = "display_scaler"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
wgpu = "0.16"
pixels = "0.13"