name: macOS

on:
  push:
    branches:
      - version_0_2_0
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  macos-arm:
    name: martypc (arm)
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cargo build
        run: cargo build -r --features ega

      - name: Copy files into install dir
        run: cp README.md target/release/martypc install

      - name: Rename install directory
        run: mv install martypc

      - name: Create artifact directory
        run: mkdir artifacts

      # GitHub zips all artifacts, losing file permissions.
      # We'll need to tar the directory in order to
      # preserve the file permissions
      - name: Create artifact from install directory
        run: tar cvf artifacts/martypc.tar martypc

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'martypc-${{ github.job }}-gha${{ github.run_number }}'
          path: artifacts/martypc.tar

  macos-x86:
    name: martypc (x86)
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cargo build
        run: cargo build -r --profile release-lto --features ega

      - name: Copy README into install dir
        run: cp README.md target/release/martypc install

      - name: Copy CHANGELOG into install dir
        run: cp CHANGELOG.md target/release/martypc install

      - name: Copy CREDITS into install dir
        run: cp CREDITS.md target/release/martypc install

      - name: Rename install directory
        run: mv install martypc

      - name: Create artifact directory
        run: mkdir artifacts

      # GitHub zips all artifacts, losing file permissions.
      # We'll need to tar the directory in order to
      # preserve the file permissions
      - name: Create artifact from install directory
        run: tar cvf artifacts/martypc.tar martypc

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'martypc-${{ github.job }}-gha${{ github.run_number }}'
          path: artifacts/martypc.tar
