name: Windows

on:
  pull_request:
    branches:
      - version_0_4_0

env:
  CARGO_TERM_COLOR: always

jobs:
  msys2:
    name: martypc
    runs-on: windows-2022

    strategy:
      matrix:
        environment:
          - msystem: MINGW64
            prefix: mingw-w64-x86_64
    steps:
      - name: Install Rust (GitHub Actions Native)
        uses: dtolnay/rust-toolchain@nightly

      - name: Prepare MSYS2 environment
        uses: msys2/setup-msys2@v2
        with:
          release: false
          update: true
          msystem: MINGW64
          # Note: Do NOT install mingw-w64-x86_64-rust
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            mingw-w64-x86_64-pkgconf
            git
            base-devel

      - name: Verify Rust in MSYS2
        shell: msys2 {0}
        run: |
          export PATH="$USERPROFILE/.cargo/bin:$PATH"
          rustc --version
          cargo --version
          rustup show active-toolchain

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Cargo Registry and Build Artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      - name: Build inside MSYS2
        shell: msys2 {0}
        run: |
          export PATH="$USERPROFILE/.cargo/bin:$PATH"
          cargo build --profile release-lto --features use_winit,use_wgpu,devtools,sound,opl

      - name: Cargo build
        run: cargo +nightly build --profile release-lto --features use_winit,use_wgpu,devtools,sound,opl

      - name: Copy files into install dir
        run: cp LICENSE README.md CHANGELOG.md CREDITS.md target/release-lto/martypc install

      - name: Rename install directory
        run: mv install martypc

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: martypc-windows-gha
          path: martypc