name: Windows

on:
  push:
    branches:
      - version_0_4_0
  pull_request:
    branches:
      - version_0_4_0

env:
  CARGO_TERM_COLOR: always

jobs:
  msys2:
    name: martypc
    runs-on: windows-2022

    defaults:
      run:
        shell: msys2 {0}

    strategy:
      matrix:
        environment:
          - msystem: MINGW64
            prefix: mingw-w64-x86_64
    steps:
      - name: Prepare MSYS2 environment
        uses: msys2/setup-msys2@v2
        with:
          release: false
          update: true
          msystem: ${{ matrix.environment.msystem }}
          pacboy: >-
            toolchain:p base-devel:p git:p curl:p

      - name: Install rustup and nightly Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustup override set nightly
          rustup show active-toolchain

      - name: Cache Cargo Registry and Build Artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cargo build
        run: cargo +nightly build --profile release-lto --features use_winit,use_wgpu,devtools,sound,opl

      - name: Copy files into install dir
        run: cp LICENSE README.md CHANGELOG.md CREDITS.md target/release-lto/martypc install

      - name: Rename install directory
        run: mv install martypc

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'martypc-windows-gha'
          path: martypc